# Generated by Django 5.1.6 on 2025-02-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
