# Generated by Django 5.1.6 on 2025-03-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off_campus', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenty',
            new_name='Amenity',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='amenties',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='image',
            new_name='images',
        ),
    ]
