# Generated by Django 5.1.6 on 2025-02-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=255)),
                ('status_verified', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=255)),
                ('student_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('Ms', 'Ms'), ('Sir', 'Sir'), ('Madam', 'Madam')], max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('status_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=255)),
                ('status_verified', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=255)),
                ('student_year', models.IntegerField()),
            ],
        ),
    ]
