# Generated by Django 5.1.6 on 2025-02-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agent_user_landlord_user_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
